"""create assignments status_history report_comments

Revision ID: 9d1b4ed464c3
Revises: 4e0f70c4f6d2
Create Date: 2026-07-19 20:26:07.643310

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by new migrations.  See:
# https://alembic.sqlalchemy.org/en/latest/api.html.html#revisions
revision = '9d1b4ed464c3'
down_revision = '4e0f70c4f6d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=False),
    sa.Column('assigned_department', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_assigned_by'), 'assignments', ['assigned_by'], unique=False)
    op.create_index(op.f('ix_assignments_assigned_to'), 'assignments', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_assignments_report_id'), 'assignments', ['report_id'], unique=False)
    op.create_table('report_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_comments_report_id'), 'report_comments', ['report_id'], unique=False)
    op.create_index(op.f('ix_report_comments_user_id'), 'report_comments', ['user_id'], unique=False)
    op.create_table('status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('previous_status', postgresql.ENUM('REPORTED', 'AI_VERIFIED', 'OFFICER_VERIFIED', 'ACKNOWLEDGED', 'ASSIGNED', 'IN_PROGRESS', 'QUALITY_CHECK', 'RESOLVED', 'CLOSED', name='reportstatus', create_type=False), nullable=False),
    sa.Column('new_status', postgresql.ENUM('REPORTED', 'AI_VERIFIED', 'OFFICER_VERIFIED', 'ACKNOWLEDGED', 'ASSIGNED', 'IN_PROGRESS', 'QUALITY_CHECK', 'RESOLVED', 'CLOSED', name='reportstatus', create_type=False), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_history_changed_by'), 'status_history', ['changed_by'], unique=False)
    op.create_index(op.f('ix_status_history_report_id'), 'status_history', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_status_history_report_id'), table_name='status_history')
    op.drop_index(op.f('ix_status_history_changed_by'), table_name='status_history')
    op.drop_table('status_history')
    op.drop_index(op.f('ix_report_comments_user_id'), table_name='report_comments')
    op.drop_index(op.f('ix_report_comments_report_id'), table_name='report_comments')
    op.drop_table('report_comments')
    op.drop_index(op.f('ix_assignments_report_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_assigned_to'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_assigned_by'), table_name='assignments')
    op.drop_table('assignments')
    # ### end Alembic commands ###
