// Five-step pothole report wizard using temporary client-side context state.
import { useNavigate } from 'react-router-dom';
import { roadTypes, severityLevels, trafficLevels } from '../../data/reportWizard';
import { useReport } from '../../context/ReportContext';
import { runAI, submitReport } from '../../services/reportService';
import { AIResultCard } from '../../components/report/AIResultCard';
import { ProgressButtons } from '../../components/report/ProgressButtons';
import { ReviewCard } from '../../components/report/ReviewCard';
import { UploadCard } from '../../components/report/UploadCard';
import { WizardStepper } from '../../components/report/WizardStepper';
import './ReportPothole.css';
export const ReportPothole = () => { const { currentStep, report, setCurrentStep, updateReport } = useReport(); const navigate = useNavigate(); const next = async () => { if (currentStep === 1 && !report.image) return; if (currentStep === 2 && (!report.location.roadName || !report.location.area)) return; if (currentStep === 3 && (!report.description || !report.roadType || !report.severity || !report.traffic)) return; if (currentStep === 4) await runAI(); if (currentStep === 5) { await submitReport(report); navigate('/report-success'); return; } setCurrentStep(currentStep + 1); }; return <main className="report-wizard"><header><p className="eyebrow">CITIZEN REPORTING</p><h1>Report a New Pothole</h1><p>Help improve road safety by reporting road damage.</p></header><WizardStepper currentStep={currentStep} />{currentStep === 1 && <UploadCard image={report.image} onImage={(image) => updateReport({ image })} />}{currentStep === 2 && <section className="report-card report-form"><h2>Location details</h2>{(['latitude', 'longitude', 'roadName', 'area', 'city', 'landmark'] as const).map((field) => <label key={field}>{field.replace(/([A-Z])/g, ' $1')}<input value={report.location[field]} onChange={(event) => updateReport({ location: { ...report.location, [field]: event.target.value } })} /></label>)}</section>}{currentStep === 3 && <section className="report-card report-form"><h2>Road damage details</h2><label>Description<textarea value={report.description} maxLength={500} onChange={(event) => updateReport({ description: event.target.value })} /></label><small>{report.description.length}/500</small><label>Road type<select value={report.roadType} onChange={(event) => updateReport({ roadType: event.target.value as typeof report.roadType })}><option value="">Select road type</option>{roadTypes.map((value) => <option key={value}>{value}</option>)}</select></label><div className="choice-grid">{severityLevels.map((value) => <button type="button" key={value} className={report.severity === value ? 'selected' : ''} onClick={() => updateReport({ severity: value })}>{value}</button>)}</div><label>Traffic level<select value={report.traffic} onChange={(event) => updateReport({ traffic: event.target.value as typeof report.traffic })}><option value="">Select traffic level</option>{trafficLevels.map((value) => <option key={value}>{value}</option>)}</select></label><label>Optional notes<textarea value={report.notes} onChange={(event) => updateReport({ notes: event.target.value })} /></label></section>}{currentStep === 4 && <AIResultCard result={report.aiResult} />}{currentStep === 5 && <ReviewCard report={report} />}<ProgressButtons currentStep={currentStep} onBack={() => setCurrentStep(currentStep - 1)} onNext={next} nextLabel={currentStep === 5 ? 'Submit Report' : 'Continue'} /></main>; };
